---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: licenses, licensing, subscriptions, annual subscription, paygo, hourly subscription, bluexp 
summary: 14일 무료 체험 기간이 종료된 후에는 두 가지 방법으로 동기화 관계에 대한 비용을 지불할 수 있습니다.  첫 번째 옵션은 AWS 또는 Azure에 가입하여 사용량에 따라 요금을 지불하거나 연간 요금을 지불하는 것입니다.  두 번째 옵션은 NetApp 에서 직접 라이선스를 구매하는 것입니다. 
---
= NetApp Copy and Sync 에 대한 라이선싱 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
14일 무료 평가판이 종료된 후에는 NetApp Copy and Sync 관계에 대한 비용을 두 가지 방법으로 지불할 수 있습니다.  첫 번째 옵션은 AWS 또는 Azure에 가입하여 사용량에 따라 요금을 지불하거나 연간 요금을 지불하는 것입니다.  두 번째 옵션은 NetApp 에서 직접 라이선스를 구매하는 것입니다.

라이선스는 NetApp Console 아닌 NetApp Copy and Sync 또는 해당 웹사이트를 통해 관리해야 합니다.



== 마켓플레이스 구독

AWS 또는 Azure에서 Copy and Sync를 구독하면 시간당 요금이나 연간 요금을 지불할 수 있습니다. link:task-licensing.html["AWS 또는 Azure를 통해 구독할 수 있습니다."] , 청구를 원하는 곳에 따라 달라집니다.

[NOTE]
====
복사 및 동기화 기능은 **AWS** 및 **Azure**의 마켓플레이스 구독만 지원합니다. Copy and Sync 기능은 Google Cloud Marketplace 구독을 지원하지 않습니다.

====


=== 시간당 구독

시간당 요금 지불 구독의 경우, 생성한 동기화 관계 수에 따라 시간당 요금이 청구됩니다.

* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["Azure에서 가격 보기"^]
* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["AWS에서 사용량에 따른 가격 책정 보기"^]




=== 연간 구독

연간 구독은 선불로 지불하는 20개의 동기화 관계에 대한 라이선스를 제공합니다.  동기화 관계가 20개를 넘고 AWS를 통해 구독한 경우, 추가 관계에 대한 비용을 시간당으로 지불해야 합니다.

https://aws.amazon.com/marketplace/pp/B06XX5V3M2["AWS의 연간 가격 보기"^]



== NetApp 의 라이센스

동기화 관계에 대한 비용을 미리 지불하는 또 다른 방법은 NetApp 에서 직접 라이선스를 구매하는 것입니다.  각 라이선스를 사용하면 최대 20개의 동기화 관계를 만들 수 있습니다.

이러한 라이선스는 AWS 또는 Azure 구독과 함께 사용할 수 있습니다.  예를 들어, 동기화 관계가 25개라면 라이선스를 사용하여 처음 20개 동기화 관계에 대한 요금을 지불한 다음, 나머지 5개 동기화 관계에 대해서는 AWS 또는 Azure에서 사용량에 따라 요금을 지불할 수 있습니다.

link:task-licensing.html["라이센스를 구매하고 NetApp Copy and Sync 에 추가하는 방법을 알아보세요."] .



=== 라이센스 조건

Copy and Sync에 BYOL(Bring Your Own License)을 구매한 고객은 라이선스 자격과 관련된 제한 사항을 알고 있어야 합니다.

* 고객은 배송일로부터 1년을 초과하지 않는 기간 동안 BYOL 라이선스를 활용할 권리가 있습니다.
* 고객은 BYOL 라이선스를 활용하여 소스와 대상 간에 총 20개의 개별 연결을 설정할 수 있으며, 이 연결은 최대 20개까지 허용됩니다(각각 "동기화 관계").
* 고객의 권한은 고객이 20개의 동기화 관계 제한에 도달했는지 여부와 관계없이 1년 라이선스 기간이 종료되면 만료됩니다.
* 고객이 라이선스를 갱신하기로 선택하는 경우, 이전 라이선스 부여와 관련된 사용되지 않은 동기화 관계는 라이선스 갱신으로 이월되지 않습니다.

