---
sidebar: sidebar 
permalink: faq.html 
keywords: community, forums, help, support, videos, faq, getting help, permissions, access control lists, acls, preserve, preserving, troubleshooting, support, encryption, smb 
summary: 포럼, 채팅 서비스, 비디오 등 다양한 리소스를 통해 NetApp Copy and Sync 대한 도움을 받고 자세한 정보를 찾아볼 수 있습니다. 
---
= NetApp Copy and Sync 기술 FAQ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 FAQ는 질문에 대한 빠른 답변을 찾는 데 도움이 될 수 있습니다.



== 시작하기

다음 질문은 NetApp Copy and Sync 시작하는 데 관한 것입니다.



=== NetApp Copy and Sync 어떻게 작동하나요?

Copy and Sync는 NetApp 데이터 브로커 소프트웨어를 사용하여 소스에서 대상으로 데이터를 동기화합니다(이를 _동기화 관계_라고 합니다).

데이터 브로커 그룹은 소스와 대상 간의 동기화 관계를 제어합니다.  동기화 관계를 설정한 후 Copy and Sync는 소스 시스템을 분석하고 이를 여러 복제 스트림으로 분할하여 선택한 대상 데이터로 푸시합니다.

최초 복사 후, 복사 및 동기화는 사용자가 설정한 일정에 따라 변경된 데이터를 동기화합니다.



=== 14일 무료 체험은 어떻게 진행되나요?

Copy and Sync에 가입하면 14일 무료 체험이 시작됩니다.  14일 동안 생성한 복사 및 동기화 관계에 대해서는 NetApp 요금이 부과되지 않습니다.  하지만 배포하는 모든 데이터 브로커에 대한 리소스 요금은 여전히 ​​적용됩니다.



=== 복사 및 동기화 비용은 얼마인가요?

Copy and Sync를 사용하는 데에는 서비스 요금과 리소스 요금이라는 두 가지 유형의 비용이 있습니다.

*서비스 요금*

사용량에 따른 가격 책정의 경우, 복사 및 동기화 서비스 요금은 귀하가 만든 동기화 관계 수에 따라 시간당으로 부과됩니다.

* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["AWS에서 사용량에 따른 가격 책정 보기"^]
* https://aws.amazon.com/marketplace/pp/B06XX5V3M2["AWS의 연간 가격 보기"^]
* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["Azure에서 가격 보기"^]


복사 및 동기화 라이선스는 NetApp 담당자를 통해서도 구매할 수 있습니다.  각 라이선스는 12개월 동안 20개의 동기화 관계를 지원합니다.

link:concept-licensing.html["라이센스에 대해 자세히 알아보세요"] .


NOTE: Azure NetApp Files 에서는 복사 및 동기화 관계가 무료입니다.

*자원 요금*

리소스 요금은 클라우드에서 데이터 브로커를 실행하는 데 드는 컴퓨팅 및 저장 비용과 관련됩니다.



=== Copy and Sync에 대한 요금은 어떻게 청구되며, 구독은 어떻게 관리하나요?

14일 무료 체험 기간이 종료된 후에는 동기화 관계에 대한 비용을 지불하는 두 가지 방법이 있습니다.  첫 번째 옵션은 AWS나 Azure에서 구독하는 것입니다. 이 경우 사용량에 따라 비용을 지불하거나 연간으로 지불할 수 있습니다.  두 번째 옵션은 NetApp 에서 직접 라이선스를 구매하는 것입니다.  어느 경우든 귀하의 구독은 Copy and Sync 사용자 인터페이스가 *아닌* 공급자 마켓플레이스를 통해 관리됩니다.



=== 클라우드 외부에서 Copy and Sync를 사용할 수 있나요?

네, 클라우드가 아닌 아키텍처에서도 복사 및 동기화 기능을 사용할 수 있습니다.  소스와 타겟은 온프레미스에 있을 수 있으며 데이터 브로커 소프트웨어도 마찬가지입니다.

클라우드 외부에서 복사 및 동기화를 사용하는 것에 대한 주요 사항은 다음과 같습니다.

* 데이터 브로커 그룹은 Copy and Sync와 통신하기 위해 인터넷 연결이 필요합니다.
* NetApp 에서 직접 라이선스를 구매하지 않으면 PAYGO 복사 및 동기화 청구를 위해 AWS 또는 Azure 계정이 필요합니다.




=== 복사 및 동기화 기능에 어떻게 접근하나요?

복사 및 동기화 기능은 NetApp Console 에서 사용할 수 있습니다.  콘솔 왼쪽 탐색에서 *모바일* > *복사 및 동기화*를 선택합니다.



=== 데이터 브로커 그룹이란 무엇인가요?

각 데이터 브로커는 데이터 브로커 그룹에 속합니다.  데이터 브로커를 그룹화하면 동기화 관계의 성능을 개선하는 데 도움이 됩니다.



== 지원되는 소스 및 대상

다음 질문은 동기화 관계에서 지원되는 소스 및 대상과 관련이 있습니다.



=== Copy and Sync는 어떤 소스와 대상을 지원합니까?

복사 및 동기화는 다양한 유형의 동기화 관계를 지원합니다. link:reference-supported-relationships.html["전체 목록 보기"] .



=== Copy and Sync는 어떤 버전의 NFS와 SMB를 지원합니까?

복사 및 동기화 기능은 NFS 버전 3 이상, SMB 버전 1 이상을 지원합니다.

link:reference-requirements.html["동기화 요구 사항에 대해 자세히 알아보세요"] .



=== Amazon S3가 대상인 경우 데이터를 특정 S3 스토리지 클래스로 계층화할 수 있습니까?

네, AWS S3가 대상인 경우 특정 S3 스토리지 클래스를 선택할 수 있습니다.

* 표준(기본 클래스)
* 지능형 계층화
* 표준-빈번하지 않은 액세스
* 1존-접근 빈도 낮음
* 빙하 심층 기록 보관소
* Glacier Flexible Retrieval
* 빙하 즉시 검색




=== Azure Blob 스토리지의 스토리지 계층은 어떻게 되나요?

Blob 컨테이너가 대상인 경우 특정 Azure Blob 저장소 계층을 선택할 수 있습니다.

* 뜨거운 보관
* 시원한 보관




=== Google Cloud 스토리지 계층을 지원하시나요?

예, Google Cloud Storage 버킷이 대상인 경우 특정 스토리지 클래스를 선택할 수 있습니다.

* 기준
* 니어라인
* 콜드라인
* 보관소




== 네트워킹

다음 질문은 Copy and Sync에 대한 네트워킹 요구 사항과 관련이 있습니다.



=== Copy and Sync에 필요한 네트워킹 요구 사항은 무엇입니까?

복사 및 동기화 환경에서는 데이터 브로커 그룹이 선택한 프로토콜이나 개체 스토리지 API(Amazon S3, Azure Blob, IBM Cloud Object Storage)를 통해 소스 및 대상에 연결되어 있어야 합니다.

또한, 데이터 브로커 그룹은 Copy and Sync와 통신하고 몇몇 다른 서비스와 저장소에 접속할 수 있도록 포트 443을 통한 아웃바운드 인터넷 연결이 필요합니다.

자세한 내용은link:reference-networking.html["네트워킹 요구 사항 검토"] .



=== 데이터 브로커와 함께 프록시 서버를 사용할 수 있나요?

네.

Copy and Sync는 기본 인증 여부와 관계없이 프록시 서버를 지원합니다.  데이터 브로커를 배포할 때 프록시 서버를 지정하는 경우 데이터 브로커의 모든 HTTP 및 HTTPS 트래픽은 프록시를 통해 라우팅됩니다.  NFS나 SMB와 같은 HTTP가 아닌 트래픽은 프록시 서버를 통해 라우팅될 수 없습니다.

유일한 프록시 서버 제한 사항은 NFS 또는 Azure NetApp Files 동기화 관계에서 전송 중 데이터 암호화를 사용할 때입니다.  암호화된 데이터는 HTTPS를 통해 전송되며 프록시 서버를 통해 라우팅할 수 없습니다.



== 데이터 동기화

다음 질문은 데이터 동기화가 작동하는 방식과 관련이 있습니다.



=== 동기화는 얼마나 자주 발생합니까?

기본 일정은 매일 동기화로 설정되어 있습니다.  초기 동기화 후에는 다음을 수행할 수 있습니다.

* 원하는 일수, 시간 또는 분으로 동기화 일정을 수정하세요.
* 동기화 일정 비활성화
* 동기화 일정을 삭제합니다(데이터는 손실되지 않으며 동기화 관계만 제거됩니다)




=== 최소 동기화 일정은 무엇입니까?

최대 1분마다 데이터를 동기화하도록 관계를 예약할 수 있습니다.



=== 파일 동기화에 실패하면 데이터 브로커 그룹이 다시 시도합니까?  아니면 시간이 초과되나요?

데이터 브로커 그룹은 단일 파일 전송에 실패해도 시간 초과가 발생하지 않습니다.  대신 데이터 브로커 그룹은 파일을 건너뛰기 전에 3번 다시 시도합니다.  재시도 값은 동기화 관계 설정에서 구성할 수 있습니다.

link:task-managing-relationships.html#change-the-settings-for-a-sync-relationship["동기화 관계의 설정을 변경하는 방법을 알아보세요"] .



=== 데이터 세트가 매우 큰 경우에는 어떻게 해야 하나요?

단일 디렉토리에 600,000개 이상의 파일이 포함되어 있는 경우link:task-get-help.html["문의하기"] 이를 통해 데이터 브로커 그룹이 페이로드를 처리하도록 구성하는 데 도움을 드릴 수 있습니다. 데이터 브로커 그룹에 추가 메모리를 추가해야 할 수도 있습니다.

마운트 지점에 있는 파일의 총 개수에는 제한이 없습니다.  60만 개 이상의 파일이 있는 대규모 디렉토리의 경우 계층 구조(최상위 디렉토리 또는 하위 디렉토리)에 관계없이 추가 메모리가 필요합니다.



== 보안

다음은 보안과 관련된 질문입니다.



=== 복사 및 동기화는 안전한가요?

네. 모든 복사 및 동기화 네트워킹 연결은 다음을 사용하여 수행됩니다. https://aws.amazon.com/sqs/["Amazon Simple Queue Service(SQS)"^] .

데이터 브로커 그룹과 Amazon S3, Azure Blob, Google Cloud Storage, IBM Cloud Object Storage 간의 모든 통신은 HTTPS 프로토콜을 통해 이루어집니다.

온프레미스(소스 또는 대상) 시스템에서 복사 및 동기화를 사용하는 경우 권장하는 몇 가지 연결 옵션은 다음과 같습니다.

* 인터넷 라우팅이 아닌 AWS Direct Connect, Azure ExpressRoute 또는 Google Cloud Interconnect 연결(지정한 클라우드 네트워크와만 통신 가능)
* 온프레미스 게이트웨이 장치와 클라우드 네트워크 간의 VPN 연결
* S3 버킷, Azure Blob 스토리지 또는 Google Cloud Storage를 사용하여 더욱 안전하게 데이터를 전송하려면 Amazon Private S3 Endpoint, Azure Virtual Network 서비스 엔드포인트 또는 Private Google Access를 설정할 수 있습니다.


이러한 방법을 사용하면 온프레미스 NAS 서버와 Copy and Sync 데이터 브로커 그룹 간에 보안 연결이 설정됩니다.



=== Copy and Sync를 사용하면 데이터가 암호화되나요?

* 복사 및 동기화는 소스 및 대상 NFS 서버 간의 전송 중 데이터 암호화를 지원합니다. link:task-nfs-encryption.html["자세히 알아보기"] .
* SMB의 경우, 복사 및 동기화는 서버 측에서 암호화한 SMB 3.0 및 3.11 데이터를 지원합니다.  복사 및 동기화는 암호화된 데이터를 소스에서 대상으로 복사하고, 대상에서는 데이터가 암호화된 상태로 유지됩니다.
+
복사 및 동기화는 SMB 데이터 자체를 암호화할 수 없습니다.

* Amazon S3 버킷이 동기화 관계의 대상인 경우 AWS KMS 암호화 또는 AES-256 암호화를 사용하여 데이터 암호화를 활성화할지 선택할 수 있습니다.
* Google Storage 버킷이 동기화 관계의 대상인 경우 기본 Google 관리 암호화 키를 사용할지, 아니면 사용자 고유의 KMS 키를 사용할지 선택할 수 있습니다.




== 권한

다음 질문은 데이터 권한과 관련이 있습니다.



=== SMB 데이터 권한이 대상 위치와 동기화되어 있습니까?

소스 SMB 공유와 대상 SMB 공유 간, 그리고 소스 SMB 공유에서 개체 스토리지( ONTAP S3 제외)로의 액세스 제어 목록(ACL)을 보존하도록 복사 및 동기화를 설정할 수 있습니다.


NOTE: 복사 및 동기화는 개체 스토리지에서 SMB 공유로 ACL을 복사하는 것을 지원하지 않습니다.

link:task-copying-acls.html["SMB 공유 간에 ACL을 복사하는 방법을 알아보세요"] .


NOTE: Copy Sync는 SMB ACL(권한)을 복사하지만 파일이나 폴더의 소유권은 복사하지 않습니다.  SMB ACL 복사 작업에는 소유권 속성이 포함되지 않습니다.  SMB 공유 간에 데이터를 복사할 때 소유권을 유지해야 하는 경우 다음을 사용하십시오. `robocopy` 보안 정보를 수동으로 복사합니다.  예를 들어, `/copyall` 플래그는 ACL, 소유자 및 감사 데이터를 복사합니다.



=== NFS 데이터 권한이 대상 위치와 동기화됩니까?

복사 및 동기화는 다음과 같이 NFS 서버 간에 NFS 권한을 자동으로 복사합니다.

* NFS 버전 3: 복사 및 동기화는 권한과 사용자 그룹 소유자를 복사합니다.
* NFS 버전 4: 복사 및 동기화는 ACL을 복사합니다.




== 개체 스토리지 메타데이터



=== 어떤 종류의 동기화 관계가 개체 저장소 메타데이터를 보존합니까?

복사 및 동기화는 다음 유형의 동기화 관계에 대해 소스에서 대상으로 개체 스토리지 메타데이터를 복사합니다.

* 아마존 S3 -> 아마존 S3 ^1^
* 아마존 S3 -> StorageGRID
* StorageGRID -> 아마존 S3
* StorageGRID -> StorageGRID
* StorageGRID -> Google 클라우드 스토리지
* Google 클라우드 스토리지 -> StorageGRID ^1^
* Google Cloud Storage -> IBM Cloud Object Storage ^1^
* 구글 클라우드 스토리지 -> 아마존 S3 ^1^
* Amazon S3 -> Google 클라우드 스토리지
* IBM Cloud Object Storage -> Google Cloud Storage
* StorageGRID -> IBM 클라우드 객체 스토리지
* IBM 클라우드 객체 스토리지 -> StorageGRID
* IBM 클라우드 객체 스토리지 -> IBM 클라우드 객체 스토리지


^1^ 이러한 동기화 관계에는 다음이 필요합니다.link:task-creating-relationships.html["동기화 관계를 생성할 때 개체 복사 설정을 활성화합니다."] .



=== NFS 또는 SMB가 소스인 동기화 중에 어떤 종류의 메타데이터가 복제됩니까?

사용자 ID, 수정 시간, 액세스 시간, GID와 같은 메타데이터는 기본적으로 복제됩니다.  사용자는 동기화 관계를 생성할 때 필수로 표시하여 CIF에서 ACL 복제를 선택할 수 있습니다.



== 성능

다음 질문은 복사 및 동기화 성능과 관련이 있습니다.



=== 동기화 관계의 진행률 표시기는 무엇을 나타냅니까?

동기화 관계는 데이터 브로커 그룹의 네트워크 어댑터의 처리량을 보여줍니다.  여러 데이터 브로커를 사용하여 동기화 성능을 가속화하는 경우 처리량은 모든 트래픽의 합계가 됩니다.  이 처리량은 20초마다 새로 고쳐집니다.



=== 성능 문제가 발생하고 있습니다.  동시 전송 수를 제한할 수 있나요?

매우 큰 파일(각각 여러 TiB)이 있는 경우 전송 프로세스를 완료하는 데 시간이 오래 걸릴 수 있으며 성능에 영향을 줄 수 있습니다.

동시 전송 수를 제한하면 도움이 될 수 있습니다. link:task-get-help.html["도움이 필요하면 저희에게 연락하세요"] .



=== Azure NetApp Files 에서 성능이 저하되는 이유는 무엇입니까?

디스크 서비스 수준이 표준인 경우 Azure NetApp Files 에서 데이터를 동기화할 때 오류 및 성능 문제가 발생할 수 있습니다.

동기화 성능을 향상시키려면 서비스 수준을 프리미엄 또는 울트라로 변경하세요.

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-service-levels#throughput-limits["Azure NetApp Files 서비스 수준 및 처리량에 대해 자세히 알아보세요."^] .



=== 그룹에는 몇 명의 데이터 브로커가 필요합니까?

새로운 관계를 만들 때는 그룹 내 단일 데이터 브로커로 시작합니다(가속 동기화 관계에 속한 기존 데이터 브로커를 선택한 경우는 제외).  많은 경우, 단일 데이터 브로커가 동기화 관계에 대한 성능 요구 사항을 충족할 수 있습니다.  그렇지 않은 경우 그룹에 추가 데이터 브로커를 추가하여 동기화 성능을 가속화할 수 있습니다.  하지만 먼저 동기화 성능에 영향을 줄 수 있는 다른 요소를 확인해야 합니다.

여러 요소가 데이터 전송 성능에 영향을 미칠 수 있습니다.  네트워크 대역폭, 지연 시간, 네트워크 토폴로지는 물론, 데이터 브로커 VM 사양과 스토리지 시스템 성능으로 인해 전반적인 동기화 성능에 영향을 받을 수 있습니다.  예를 들어, 그룹 내 단일 데이터 브로커는 최대 100MB/s에 도달할 수 있는 반면, 대상의 디스크 처리량은 최대 64MB/s만 허용할 수 있습니다.  결과적으로 데이터 브로커 그룹은 계속해서 데이터를 복사하려고 시도하지만 대상은 데이터 브로커 그룹의 성능을 충족할 수 없습니다.

따라서 대상의 네트워킹 성능과 디스크 처리량을 꼭 확인하세요.

그런 다음 그룹에 추가 데이터 브로커를 추가하여 해당 관계의 부하를 공유함으로써 동기화 성능을 가속화하는 것을 고려할 수 있습니다. link:task-managing-relationships.html#accelerate-sync-performance["동기화 성능을 가속화하는 방법을 알아보세요"] .



== 삭제하기

다음 질문은 소스와 대상에서 동기화 관계와 데이터를 삭제하는 것과 관련이 있습니다.



=== 복사 및 동기화 관계를 삭제하면 어떻게 되나요?

관계를 삭제하면 향후 모든 데이터 동기화가 중단되고 결제가 종료됩니다.  대상과 동기화된 모든 데이터는 그대로 유지됩니다.



=== 소스 서버에서 무언가를 삭제하면 어떻게 되나요?  타겟에서도 제거되나요?

기본적으로 활성 동기화 관계가 있는 경우 소스 서버에서 삭제된 항목은 다음 동기화 중에 대상 서버에서 삭제되지 않습니다.  하지만 각 관계에 대한 동기화 설정에는 소스에서 파일이 삭제된 경우 복사 및 동기화를 통해 대상 위치에서도 파일이 삭제되도록 정의할 수 있는 옵션이 있습니다.

link:task-managing-relationships.html#change-the-settings-for-a-sync-relationship["동기화 관계의 설정을 변경하는 방법을 알아보세요"] .



=== 타겟에서 무언가를 삭제하면 어떻게 되나요?  내 소스에서도 제거되나요?

대상에서 항목을 삭제해도 소스에서는 삭제되지 않습니다.  관계는 일방적, 즉 출처에서 대상으로 향하는 관계입니다.  다음 동기화 주기에서 복사 및 동기화는 소스와 대상을 비교하여 항목이 누락되었음을 확인하고, 복사 및 동기화는 해당 항목을 소스에서 대상으로 다시 복사합니다.



== 문제 해결

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Sync/Cloud_Sync_FAQ:_Support_and_Troubleshooting["NetApp 지식 기반: 복사 및 동기화 FAQ: 지원 및 문제 해결"^]



== 데이터 브로커 심층 분석

다음 질문은 데이터 브로커와 관련이 있습니다.



=== 데이터 브로커의 아키텍처를 설명해 주시겠습니까?

확신하는.  가장 중요한 사항은 다음과 같습니다.

* 데이터 브로커는 Linux 호스트에서 실행되는 node.js 애플리케이션입니다.
* Copy and Sync는 다음과 같이 데이터 브로커를 배포합니다.
+
** AWS: AWS CloudFormation 템플릿에서
** Azure: Azure Resource Manager에서
** Google: Google Cloud Deployment Manager에서
** 자신의 Linux 호스트를 사용하는 경우 소프트웨어를 수동으로 설치해야 합니다.


* 데이터 브로커 소프트웨어는 자동으로 최신 버전으로 업그레이드됩니다.
* 데이터 브로커는 AWS SQS를 안정적이고 안전한 통신 채널로 사용하고 제어 및 모니터링을 위해 사용합니다.  SQS는 또한 지속성 계층을 제공합니다.
* 그룹에 추가 데이터 브로커를 추가하여 전송 속도를 높이고 가용성을 높일 수 있습니다.  하나의 데이터 브로커에 장애가 발생하더라도 서비스 회복성이 있습니다.

