---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: 14일 무료 체험 기간이 종료된 후에는 두 가지 방법으로 동기화 관계에 대한 비용을 지불할 수 있습니다.  첫 번째 옵션은 사용량에 따라 요금을 지불하는 것입니다.  두 번째 옵션은 NetApp 에서 직접 라이선스를 구매하는 것입니다. 
---
= NetApp Copy and Sync 무료 평가판이 종료된 후 동기화 관계에 대한 비용을 지불하세요.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Copy and Sync의 14일 무료 평가판이 종료된 후에는 동기화 관계에 대한 비용을 두 가지 방법으로 지불할 수 있습니다.  첫 번째 옵션은 AWS 또는 Azure에 가입하여 사용량에 따라 요금을 지불하거나 연간 요금을 지불하는 것입니다.  두 번째 옵션은 NetApp 에서 직접 라이선스를 구매하는 것입니다.

AWS Marketplace나 Azure Marketplace에서 구독할 수 있습니다.  두 곳 모두에서 구독할 수는 없습니다.

마켓플레이스 구독을 통해 NetApp 라이선스를 사용할 수 있습니다.  예를 들어, 동기화 관계가 25개라면 라이선스를 사용하여 처음 20개 동기화 관계에 대한 요금을 지불한 다음, 나머지 5개 동기화 관계에 대해서는 AWS 또는 Azure에서 사용량에 따라 요금을 지불할 수 있습니다.

link:concept-licensing.html["라이센스 작동 방식에 대해 자세히 알아보세요"] .

무료 체험 기간이 종료된 후 즉시 결제하지 않으면 추가 관계를 생성할 수 없습니다.  기존 관계는 삭제되지 않지만, 구독하거나 라이선스를 입력하기 전까지는 관계를 변경할 수 없습니다.

라이선스는 NetApp Copy and Sync 또는 해당 웹사이트를 통해 관리해야 하며 NetApp 콘솔 구독을 통해서는 관리하지 않습니다.



== [[aws]]AWS 구독

AWS를 사용하면 사용량에 따라 비용을 지불하거나 연간으로 지불할 수 있습니다.

.사용량에 따른 결제 단계
. NetApp 콘솔 탐색 메뉴에서 *모빌리티 > 복사 및 동기화*를 선택합니다.
. *라이선스*를 선택하세요.
. *AWS*을 선택하세요.
. *구독*을 선택한 다음 *계속*을 선택하세요.
. AWS Marketplace에서 구독한 다음 Copy and Sync에 다시 로그인하여 등록을 완료하세요.
+
다음 영상은 그 과정을 보여줍니다.

+
.AWS Marketplace에서 복사 및 동기화 구독
video::796ffd6d-cade-4750-8504-b24c010b225d[panopto]


.연간 지불 단계
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["AWS Marketplace 페이지로 이동"^] .
. *구독 계속하기*를 선택하세요.
. 계약 옵션을 선택한 다음 *계약 생성*을 선택하세요.




== [[azure]]Azure에서 구독

Azure를 사용하면 사용량에 따라 요금을 지불하거나 연간 요금을 지불할 수 있습니다.

.필요한 것
해당 구독에서 기여자 또는 소유자 권한이 있는 Azure 사용자 계정입니다.

.단계
. NetApp 콘솔 탐색 메뉴에서 *모빌리티 > 복사 및 동기화*를 선택합니다.
. *라이선스*를 선택하세요.
. *Azure*를 선택하세요.
. *구독*을 선택한 다음 *계속*을 선택하세요.
. Azure Portal에서 *만들기*를 선택하고 옵션을 선택한 다음 *구독*을 선택합니다.
+
시간당 결제를 원하시면 *월별*을 선택하시고, 1년치를 선불로 결제하려면 *연별*을 선택하세요.

. 배포가 완료되면 알림 팝업에서 SaaS 리소스 이름을 선택합니다.
. 복사 및 동기화로 돌아가려면 *계정 구성*을 선택하세요.
+
다음 영상은 그 과정을 보여줍니다.

+
.Azure Marketplace에서 복사 및 동기화 구독
video::a6a39447-b7b1-42f6-9c89-b24c010b21b9[panopto]




== [[라이센스]] NetApp 에서 라이센스를 구매하고 Copy and Sync에 추가합니다.

동기화 관계에 대한 비용을 선불로 지불하려면 하나 이상의 라이선스를 구매하여 Copy and Sync에 추가해야 합니다.

.필요한 것
라이선스의 일련 번호와 라이선스가 연결된 NetApp 지원 사이트 계정의 사용자 이름과 비밀번호가 필요합니다.

.단계
. mailto:ng-cloudsync-contact@netapp.com?subject=Cloud%20Sync%20Service%20-%20BYOL%20License%20Purchase%20Request[ NetApp 에 ​​문의]로 라이선스를 구매하세요.
. link:task-login-copyandsync.html["복사 및 동기화에 로그인하세요"] .
. *라이선스*를 선택하세요.
. *라이선스 추가*를 선택하고 필요한 정보를 추가하세요.
+
.. 일련번호를 입력하세요.
.. 추가하려는 라이선스와 연결된 NetApp 지원 사이트 계정을 선택하세요.
+
*** 계정이 이미 NetApp 콘솔에 추가된 경우 드롭다운 목록에서 해당 계정을 선택하세요.
*** 아직 계정이 추가되지 않은 경우 *NSS 자격 증명 추가*를 선택하고 사용자 이름과 비밀번호를 입력한 다음 *등록*을 선택하고 드롭다운 목록에서 해당 계정을 선택하세요.


.. *추가*를 선택하세요.






== 라이센스 업데이트

NetApp 에서 구매한 복사 및 동기화 라이선스를 연장한 경우, 새로운 만료 날짜가 복사 및 동기화에서 자동으로 업데이트되지 않습니다.  만료 날짜를 새로 고치려면 라이선스를 다시 추가해야 합니다.  라이선스는 NetApp 콘솔 구독이 아닌 Copy and Sync 또는 해당 웹사이트를 통해 관리해야 합니다.

.단계
. NetApp 콘솔 탐색 메뉴에서 *모빌리티 > 복사 및 동기화*를 선택합니다.
. *라이선스*를 선택하세요.
. *라이선스 추가*를 선택하고 필요한 정보를 추가하세요.
+
.. 일련번호를 입력하세요.
.. 추가하려는 라이선스와 연결된 NetApp 지원 사이트 계정을 선택하세요.
.. *추가*를 선택하세요.




.결과
복사 및 동기화는 기존 라이센스를 새로운 만료 날짜로 업데이트합니다.
